"""video_models

Revision ID: 21d6ca6be17f
Revises: 66689b718c8c
Create Date: 2025-05-05 13:40:36.798214

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "21d6ca6be17f"
down_revision: Union[str, None] = "66689b718c8c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "videos",
        sa.Column(
            "id",
            sa.CHAR(length=26),
            server_default=sa.text("generate_ulid()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column("path", sa.CHAR(length=30), nullable=False),
        sa.Column(
            "process_status",
            sa.Enum(
                "PENDING",
                "PROCESSING",
                "COMPLETED",
                "FAILED",
                name="videoprocessstatus",
            ),
            server_default="PENDING",
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_videos_process_status"), "videos", ["process_status"], unique=False
    )
    op.create_table(
        "video_frames",
        sa.Column("timestamp", sa.INTEGER(), nullable=False),
        sa.Column("frame_number", sa.INTEGER(), nullable=False),
        sa.Column("video_id", sa.CHAR(length=26), nullable=False),
        sa.ForeignKeyConstraint(["video_id"], ["videos.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("frame_number", "video_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("video_frames")
    op.drop_index(op.f("ix_videos_process_status"), table_name="videos")
    op.drop_table("videos")
    # ### end Alembic commands ###
